f1bets/Controllers/CompetitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using f1bets.ViewModels;
using Models;
using Repositories;
using Repositories.RepositoryContexts;

namespace f1bets.Controllers
{
    public class CompetitionController : Controller
    {
        private CompetitionRepository repo = new CompetitionRepository(new CompetitionRepositorySQLContext());
        private UserRepository userRepo = new UserRepository(new UserRepositorySQLContext());

        public IActionResult Index()
        {
            try
            {
                List<Competition> competitions = repo.GetUpcomingCompetitions();
                return View(competitions);
            }
            catch (Exception)
            {
                //connection error page
                return View("Error");
            }
        }

        public IActionResult History()
        {
            try
            {
                List<Competition> pastCompetitions = repo.GetPastCompetitions();
                return View(pastCompetitions);
            }
            catch (Exception)
            {
                //connection error page
                return View("Error");
            }
        }

        public IActionResult Details(int id)
        {
            try
            {
                DetailsViewModel vm = new DetailsViewModel();
                vm.Competition = repo.GetCompetition(id);
                vm.Drivers = repo.GetDrivers();
                ViewBag.Reactions = repo.GetReactions(id);
                if (vm.Competition.Date < DateTime.Now)
                {
                    vm.Results = repo.GetResultsFromRace(vm.Competition.ID);
                }
                ViewBag.CompetitionData = vm;

                PredictionViewModel p = new PredictionViewModel();
                return View(p);
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        [HttpPost]
        public IActionResult AddReaction(Reaction r)
        {
            string username = HttpContext.Session.GetString("Account");
            if (username != null)
            {
                try
                {
                    r.User = userRepo.GetUser(username);
                    repo.AddReaction(r);

                    return RedirectToRoute("competition", new { action = "Details", id = r.Competition_id });
                }
                catch (Exception)
                {
                    return View("Error");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public IActionResult AddReply(Reaction r)
        {
            string username = HttpContext.Session.GetString("Account");
            if (username != null)
            {
                try
                {
                    r.User = userRepo.GetUser(username);
                    repo.AddReply(r, r.Replyto_id);

                    return RedirectToRoute("competition", new { action = "Details", id = r.Competition_id });
                }
                catch (Exception)
                {
                    return View("Error");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

f1bets/Controllers/F1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Models;
using Repositories;
using Repositories.RepositoryContexts;
using f1bets.ViewModels;

namespace f1bets.Controllers
{
    public class F1Controller : Controller
    {
        private F1Repository repo = new F1Repository(new F1RepositorySQLContext());
        public IActionResult Index()
        {
            ViewBag.Drivers = repo.GetDrivers();
            ViewBag.Teams = repo.GetTeams();
            return View();
        }

        public IActionResult Drivers(int? id)
        {
            DriverViewModel vm = new DriverViewModel();
            vm.Driver = repo.GetDriver(id);
            vm.Results = repo.GetDriverResults(id);
            return View(vm);
        }

        public IActionResult Teams(int? id)
        {
            Team t = repo.GetTeam(id);
            return View(t);
        }
    }
}

f1bets/Views/Shared/UserNotFound.cshtml
@{ 
    ViewData["Title"] = "User not found";
}

<div class="alert alert-danger" role="alert" style="margin-top: 25px">
    <h4 class="text-danger"><span class="glyphicon glyphicon-alert"></span>  An error has occurred while processing your request.</h4>
    <p>The profile you are trying to visit does not exist.</p>
</div>

f1bets/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@using Microsoft.AspNetCore.Http
@using Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - f1bets</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">f1bets</a>
            </div>
            <div class="navbar-collapse collapse navbar-left">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Competition" asp-action="Index">Competitions</a></li>
                    <li><a asp-area="" asp-controller="F1" asp-action="Index">F1DB</a></li>
                </ul>
            </div>
            <div class="nav navbar-nav navbar-right btn-group">
                @if (Context.Session.Get("Account") == null)
                {
                    <button type="button" class="btn btn-primary navbar-btn" onclick="location.href='@Url.Action("LogIn", "User")'">Log In</button>
                    <button type="button" class="btn btn-primary navbar-btn" onclick="location.href='@Url.Action("Register", "User")'">Register</button>
                }
                else
                {
                    <button type="button" class="btn btn-primary navbar-btn" onclick="location.href='@Url.RouteUrl("user", new { controller = "User", Action = "Profile", Username = Context.Session.GetString("Account") })'">My Profile</button>
                    <button class="btn btn-primary dropdown-toggle navbar-btn" type="button" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-option-vertical"></span>
                    </button>
                    <ul class="dropdown-menu" style="width: 180px">
                        <li><a asp-area="" asp-controller="Prediction" asp-action="Index">My Predictions</a></li>
                        <li><a asp-area="" asp-controller="User" asp-action="Friends">My Friends<span class="glyphicon glyphicon-user pull-right"></span></a></li>
                        <li><a asp-area="" asp-controller="User" asp-action="Settings">Account Settings<span class="glyphicon glyphicon-cog pull-right"></span></a></li>
                        <li role="separator" class="divider"></li>
                        <li><a asp-area="" asp-controller="User" asp-action="LogOut">Log Out<span class="glyphicon glyphicon-log-out pull-right"></span></a></li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - f1bets</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>    
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>